version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-source-plugin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
